let allMusic = [
  {
    name: "Apna Bana Le",
    artist: "Arjit Singh",
    album: "Bhediya",
    img: "apnabanale",
    artistImg: "arjit-singh",
    albumImg: "bhediya",
    src: "song-1",
  },
  {
    name: "Nafrat",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "nafrat",
    artistImg: "darshanraval",
    albumImg: "ilovedyou",
    src: "song-2",
  },
  {
    name: "Deewana",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "deewana",
    artistImg: "darshanraval",
    albumImg: "ilovedyou",
    src: "song-3",
  },
  {
    name: "Haara",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "haara",
    artistImg: "darshanraval",
    albumImg: "ilovedyou",
    src: "song-4",
  },
  {
    name: "Jiyaa",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "jiyaa",
    artistImg: "darshanraval",
    albumImg: "ilovedyou",
    src: "song-5",
  },
];

