let allMusic = [
  {
    name: "Apna Bana Le",
    artist: "Arjit Singh",
    album: "Bhediya",
    img: "apnabanale",
    artistImg: "arjit-singh",
    albumImg: "bhediya",
    src: "song-1",
  },
  {
    name: "Nafrat",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "nafrat",
    artistImg: "darshanraval",
    albumImg: "ilovedyou",
    src: "song-2",
  },
  {
    name: "Deewana",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "deewana",
    artistImg: "darshanraval",
    albumImg: "ilovedyou",
    src: "song-3",
  },
  {
    name: "Haara",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "haara",
    artistImg: "darshanraval",
    albumImg: "ilovedyou",
    src: "song-4",
  },
  {
    name: "Jiyaa",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "jiyaa",
    artistImg: "darshanraval",
    albumImg: "ilovedyou",
    src: "song-5",
  },
  {
    name: "Khwaab",
    artist: "Faheem Abdullah",
    album: "Lost;Found",
    img: "LostFound",
    artistImg: "faheem-abdullah",
    albumImg: "Lost;Found",
    src: "song-6",
  },
  {
    name: "Ishq",
    artist: "Faheem Abdullah",
    album: "Lost;Found",
    img: "LostFound",
    artistImg: "faheem-abdullah",
    albumImg: "Lost;Found",
    src: "song-7",
  },
  {
    name: "Sajde",
    artist: "Faheem Abdullah",
    album: "Lost;Found",
    img: "LostFound",
    artistImg: "faheem-abdullah",
    albumImg: "Lost;Found",
    src: "song-8",
  },
  {
    name: "Teri Yaad",
    artist: "Faheem Abdullah",
    album: "Teri Yaad",
    img: "teriyaad",
    artistImg: "faheem-abdullah",
    albumImg: "teriyaad",
    src: "song-9",
  },
  {
    name: "Jaana Nahi",
    artist: "Faheem Abdullah",
    album: "Jaana Nahi",
    img: "jaananahi",
    artistImg: "faheem-abdullah",
    albumImg: "jaananahi",
    src: "song-10",
  },
  {
    name: "Aawaara Angaara",
    artist: "Faheem Abdullah",
    album: "Tere Ishq Mein",
    img: "aawaaraangaara",
    artistImg: "faheem-abdullah",
    albumImg: "tereishqmein",
    src: "song-11",
  },
  {
    name: "Ae Yaad",
    artist: "Faheem Abdullah",
    album: "Ae Yaad",
    img: "aeyaad",
    artistImg: "faheem-abdullah",
    albumImg: "aeyaad",
    src: "song-12",
  },
];

