let allMusic = [
  {
    name: "Apna Bana Le",
    artist: "Arjit Singh",
    album: "Bhediya",
    img: "apnabanale",
    artistImg: "arjit-singh",
    albumImg: "bhediya",
    src: "apnabanale",
  },
  {
    name: "Nafrat",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "nafrat",
    artistImg: "darshan-raval",
    albumImg: "ilovedyou",
    src: "nafrat",
  },
  {
    name: "Deewana",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "deewana",
    artistImg: "darshan-raval",
    albumImg: "ilovedyou",
    src: "deewana",
  },
  {
    name: "Haara",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "haara",
    artistImg: "darshan-raval",
    albumImg: "ilovedyou",
    src: "haara",
  },
  {
    name: "Jiyaa",
    artist: "Darshan Raval",
    album: "I Loved You",
    img: "jiyaa",
    artistImg: "darshan-raval",
    albumImg: "ilovedyou",
    src: "jiyaa",
  },
];

